# Generated by Django 5.0.6 on 2024-05-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
